#!/usr/bin/env python
import sys,os
sys.path.insert(0,'.')
import logging
import utils.log as log

def run_in_debug():
    gettrace=getattr(sys,'gettrace',None)
    if gettrace is None:
        return False
    elif gettrace():
        return True
    else:
        return None
try:
    log.level = logging.DEBUG
    #log.level = logging.INFO
    log.level = logging.WARNING
    #log.level = logging.ERROR
    log.debug("Importing hwdetector")
    import hwdetector

    log.debug("Instantiate HwDetector")
    hwd=hwdetector.HwDetector()
    #hwd.all_plugins_are_needed=True
    if not run_in_debug():
        print 'USING MAX_RUNNING_TIME !!!'
        hwd.MAX_RUNNING_TIME = 5
    #hwd.fake_capabilities={'IAMGOD':'yes'}
    log.debug("Calling run plugins")
    #ret = hwd.run(needs=['ALL_TESTS'])
    #ret = hwd.run(needs=['LLXSYSTEM_TEST','LLXNETWORK_TEST'])
    ret = hwd.run()
    #print('\nCapabilities stored (with values)\n')
    #hwd.printCapabilities()
    #print('\nCapabilities stored({}) = {}\n'.format(len(hwd.capabilities_stored),','.join(hwd.capabilities_stored)))
    print("Total running time: {}".format(hwd.RUNNING_TIME))
    if ret:
        print "Exit code = 0"
        sys.exit(0)
    else:
        print "Exit code = 1"
        sys.exit(1)
except Exception as e:
    print("Exception occurred: {}".format(e))
    print "Exit code = 1"
    sys.exit(1)
    pass

